/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;

/**
 *
 * @author LATYR
 */
public class acceuilleAdmin extends javax.swing.JFrame {

    /**
     * Creates new form acceuilleAdmin
     */
    public acceuilleAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        font = new javax.swing.JPanel();
        departement = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        Matricule = new javax.swing.JLabel();
        deconnexion = new javax.swing.JButton();
        modifierProfil = new javax.swing.JButton();
        acceuilleAdmin = new javax.swing.JPanel();
        deliberation = new javax.swing.JButton();
        titre = new javax.swing.JLabel();
        ajouterEtudiant = new javax.swing.JButton();
        ajouterENS = new javax.swing.JButton();
        ajouterMatiere = new javax.swing.JButton();
        prenom = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(150, 80));
        setMinimumSize(new java.awt.Dimension(900, 500));

        font.setBackground(new java.awt.Color(119, 181, 254));
        font.setLayout(null);

        departement.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        departement.setForeground(new java.awt.Color(255, 255, 255));
        font.add(departement);
        departement.setBounds(130, 100, 100, 40);

        photo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 3, true));
        font.add(photo);
        photo.setBounds(0, 0, 120, 140);

        Matricule.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Matricule.setForeground(new java.awt.Color(255, 255, 255));
        font.add(Matricule);
        Matricule.setBounds(120, 0, 110, 40);

        deconnexion.setBackground(new java.awt.Color(0, 153, 153));
        deconnexion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deconnexion.setForeground(new java.awt.Color(255, 255, 255));
        deconnexion.setText("DECONNEXION");
        deconnexion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionActionPerformed(evt);
            }
        });
        font.add(deconnexion);
        deconnexion.setBounds(0, 360, 160, 40);

        modifierProfil.setBackground(new java.awt.Color(0, 153, 153));
        modifierProfil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modifierProfil.setForeground(new java.awt.Color(255, 255, 255));
        modifierProfil.setText("MODIFIER-PROFIL");
        modifierProfil.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        modifierProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierProfilActionPerformed(evt);
            }
        });
        font.add(modifierProfil);
        modifierProfil.setBounds(0, 160, 160, 40);

        acceuilleAdmin.setBackground(new java.awt.Color(0, 153, 153));
        acceuilleAdmin.setLayout(null);

        deliberation.setBackground(new java.awt.Color(119, 181, 254));
        deliberation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deliberation.setText("DELIBERATION");
        deliberation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        deliberation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliberationActionPerformed(evt);
            }
        });
        acceuilleAdmin.add(deliberation);
        deliberation.setBounds(320, 310, 210, 40);

        titre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(255, 255, 255));
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("ACCEUILLE ADMIN");
        titre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true));
        acceuilleAdmin.add(titre);
        titre.setBounds(90, 40, 460, 60);

        ajouterEtudiant.setBackground(new java.awt.Color(119, 181, 254));
        ajouterEtudiant.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ajouterEtudiant.setText("AJOUTER ETUDIANT");
        ajouterEtudiant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ajouterEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterEtudiantActionPerformed(evt);
            }
        });
        acceuilleAdmin.add(ajouterEtudiant);
        ajouterEtudiant.setBounds(70, 230, 210, 40);

        ajouterENS.setBackground(new java.awt.Color(119, 181, 254));
        ajouterENS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ajouterENS.setText("AJOUTER ENSEIGNANT");
        ajouterENS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ajouterENS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterENSActionPerformed(evt);
            }
        });
        acceuilleAdmin.add(ajouterENS);
        ajouterENS.setBounds(320, 230, 210, 40);

        ajouterMatiere.setBackground(new java.awt.Color(119, 181, 254));
        ajouterMatiere.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ajouterMatiere.setText("AJOUTER MATIERE");
        ajouterMatiere.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        ajouterMatiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterMatiereActionPerformed(evt);
            }
        });
        acceuilleAdmin.add(ajouterMatiere);
        ajouterMatiere.setBounds(70, 310, 210, 40);

        prenom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        prenom.setForeground(new java.awt.Color(255, 255, 255));
        acceuilleAdmin.add(prenom);
        prenom.setBounds(-40, 30, 100, 40);

        font.add(acceuilleAdmin);
        acceuilleAdmin.setBounds(230, -10, 680, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(font, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(font, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionActionPerformed
        // TODO add your handling code here:
        connectionAdmin connectAdmin = new connectionAdmin();
        connectAdmin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_deconnexionActionPerformed

    private void modifierProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierProfilActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        modifierPhoto modif= new modifierPhoto();
        modif.setVisible(true);
    }//GEN-LAST:event_modifierProfilActionPerformed

    private void deliberationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliberationActionPerformed
         deliberation delb = new deliberation();
         delb.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_deliberationActionPerformed

    private void ajouterEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterEtudiantActionPerformed
        // TODO add your handling code here:
        ajouterEtudiant pageAjoutEtu = new ajouterEtudiant();
         pageAjoutEtu.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_ajouterEtudiantActionPerformed

    private void ajouterENSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterENSActionPerformed
        // TODO add your handling code here:
        ajouterEnseignant ajoutEns = new ajouterEnseignant();
        ajoutEns.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ajouterENSActionPerformed

    private void ajouterMatiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterMatiereActionPerformed
        // TODO add your handling code here:
        ajouterMatiere pageMatiere = new ajouterMatiere();
        pageMatiere.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ajouterMatiereActionPerformed
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(acceuilleAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(acceuilleAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(acceuilleAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(acceuilleAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new acceuilleAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Matricule;
    private javax.swing.JPanel acceuilleAdmin;
    private javax.swing.JButton ajouterENS;
    private javax.swing.JButton ajouterEtudiant;
    private javax.swing.JButton ajouterMatiere;
    private javax.swing.JButton deconnexion;
    private javax.swing.JButton deliberation;
    private javax.swing.JLabel departement;
    private javax.swing.JPanel font;
    private javax.swing.JButton modifierProfil;
    private javax.swing.JLabel photo;
    private javax.swing.JLabel prenom;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
