/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author LATYR
 */
public class AcceuilEtudiant extends javax.swing.JFrame {
    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form AcceuilEtudiant
     */
    public AcceuilEtudiant() {
        initComponents();
        tableauNote();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        font = new javax.swing.JPanel();
        departement = new javax.swing.JLabel();
        Matricule = new javax.swing.JLabel();
        deconnexion = new javax.swing.JButton();
        acceuilleAdmin = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        tableauInfoEtu = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 30));
        setMinimumSize(new java.awt.Dimension(1020, 800));
        getContentPane().setLayout(null);

        font.setBackground(new java.awt.Color(119, 181, 254));
        font.setLayout(null);

        departement.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        departement.setForeground(new java.awt.Color(255, 255, 255));
        font.add(departement);
        departement.setBounds(130, 100, 100, 40);

        Matricule.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Matricule.setForeground(new java.awt.Color(255, 255, 255));
        font.add(Matricule);
        Matricule.setBounds(120, 0, 110, 40);

        deconnexion.setBackground(new java.awt.Color(0, 153, 153));
        deconnexion.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deconnexion.setForeground(new java.awt.Color(255, 255, 255));
        deconnexion.setText("DECONNEXION");
        deconnexion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionActionPerformed(evt);
            }
        });
        font.add(deconnexion);
        deconnexion.setBounds(0, 360, 160, 40);

        acceuilleAdmin.setBackground(new java.awt.Color(0, 153, 153));
        acceuilleAdmin.setLayout(null);

        titre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(255, 255, 255));
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("ACCEUILLE ETUDIANT");
        titre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true));
        acceuilleAdmin.add(titre);
        titre.setBounds(120, 30, 460, 60);

        prenom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        prenom.setForeground(new java.awt.Color(255, 255, 255));
        acceuilleAdmin.add(prenom);
        prenom.setBounds(-40, 30, 100, 40);

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        tableauInfoEtu.setViewportView(jTable1);

        acceuilleAdmin.add(tableauInfoEtu);
        tableauInfoEtu.setBounds(10, 150, 740, 320);

        font.add(acceuilleAdmin);
        acceuilleAdmin.setBounds(190, 0, 820, 650);

        getContentPane().add(font);
        font.setBounds(0, 0, 1050, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionActionPerformed
        // TODO add your handling code here:
        connectionAdmin connectAdmin = new connectionAdmin();
        connectAdmin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_deconnexionActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        //   Date date = (Date) dateDeNaissance.getDate();
        int selectionner= jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       // textINE.setText(model.getValueAt(selectionner, 0).toString());
       // textMatiere.setText(model.getValueAt(selectionner, 1).toString());
        //  dateDeNaissance.setText(model.getValueAt(selectionner, 2).toString());
    }//GEN-LAST:event_jTable1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcceuilEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcceuilEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcceuilEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcceuilEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
     
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcceuilEtudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Matricule;
    private javax.swing.JPanel acceuilleAdmin;
    private javax.swing.JButton deconnexion;
    private javax.swing.JLabel departement;
    private javax.swing.JPanel font;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel prenom;
    private javax.swing.JScrollPane tableauInfoEtu;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables

    private void tableauNote() {
               connexion connect = new connexion();
        String colonne[] ={"INE","PRENOM","NOM","NOTE","CREDIT","MATIERE"};
        DefaultTableModel model = new DefaultTableModel(null,colonne) ;
        PreparedStatement st ;
        ResultSet RS;
        try{
           
            
           st = connect.con.prepareStatement("SELECT etudiant.nomEtu, etudiant.prenomEtu, etudiant.INE, notes.note,notes.credit, matiere.nomMat \n" +
            "FROM etudiant \n" +
            "INNER JOIN notes ON etudiant.INE = notes.INEETU \n" +
            "INNER JOIN matiere ON notes.codeMat = matiere.codeMat \n");
           RS= st.executeQuery();
           //if(textINE.getText().isEmpty()){
               
           //}else{
                while(RS.next()){
                    Object o[]= {
                         RS.getString("INE"),
                        RS.getString("prenomEtu"),
                        RS.getString("nomEtu"),
                        RS.getString("note"),
                        RS.getString("credit"),
                        RS.getString("nomMat"),
                    };
                     model.addRow(o);
                };
                jTable1.setModel(model);
           
        }catch(Exception e){
            e.printStackTrace();
        }
    }
}
