/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.JOptionPane;
/**
 *
 * @author LATYR
 */
public class ajouterEnseignant extends javax.swing.JFrame {
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form ajouterEnseignant
     */
    public ajouterEnseignant() {
        initComponents();
        tableauEnseignant();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textPrenom = new javax.swing.JTextField();
        titre = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        textNom = new javax.swing.JTextField();
        nom = new javax.swing.JLabel();
        textMatiere = new javax.swing.JTextField();
        codeMatiere = new javax.swing.JLabel();
        enregistrer = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        retour = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        supprimer = new javax.swing.JButton();
        rechercher = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 40));

        jPanel1.setBackground(new java.awt.Color(119, 181, 254));
        jPanel1.setLayout(null);

        textPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrenomActionPerformed(evt);
            }
        });
        textPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textPrenomKeyReleased(evt);
            }
        });
        jPanel1.add(textPrenom);
        textPrenom.setBounds(480, 130, 210, 30);

        titre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(255, 255, 255));
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("GESTION DES ENSEIGNANTS");
        titre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true));
        jPanel1.add(titre);
        titre.setBounds(310, 10, 460, 60);

        prenom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        prenom.setForeground(new java.awt.Color(255, 255, 255));
        prenom.setText("PRENOM:");
        jPanel1.add(prenom);
        prenom.setBounds(370, 130, 100, 30);

        textNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomActionPerformed(evt);
            }
        });
        jPanel1.add(textNom);
        textNom.setBounds(480, 180, 210, 30);

        nom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.setText("NOM:");
        jPanel1.add(nom);
        nom.setBounds(400, 180, 140, 30);

        textMatiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMatiereActionPerformed(evt);
            }
        });
        jPanel1.add(textMatiere);
        textMatiere.setBounds(480, 230, 210, 30);

        codeMatiere.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        codeMatiere.setForeground(new java.awt.Color(255, 255, 255));
        codeMatiere.setText("CODE MATIERE:");
        jPanel1.add(codeMatiere);
        codeMatiere.setBounds(310, 230, 160, 30);

        enregistrer.setBackground(new java.awt.Color(0, 153, 153));
        enregistrer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enregistrer.setForeground(new java.awt.Color(255, 255, 255));
        enregistrer.setText("ENREGISTRER");
        enregistrer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });
        jPanel1.add(enregistrer);
        enregistrer.setBounds(230, 320, 160, 40);

        modifier.setBackground(new java.awt.Color(0, 153, 153));
        modifier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modifier.setForeground(new java.awt.Color(255, 255, 255));
        modifier.setText("MODIFIER");
        modifier.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        jPanel1.add(modifier);
        modifier.setBounds(440, 320, 160, 40);

        retour.setBackground(new java.awt.Color(0, 153, 153));
        retour.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        retour.setForeground(new java.awt.Color(255, 255, 255));
        retour.setText("HOME");
        retour.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        jPanel1.add(retour);
        retour.setBounds(860, 320, 160, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 400, 1090, 230);

        supprimer.setBackground(new java.awt.Color(0, 153, 153));
        supprimer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        supprimer.setForeground(new java.awt.Color(255, 255, 255));
        supprimer.setText("SUPPRIMER");
        supprimer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        jPanel1.add(supprimer);
        supprimer.setBounds(650, 320, 160, 40);

        rechercher.setBackground(new java.awt.Color(0, 153, 153));
        rechercher.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rechercher.setForeground(new java.awt.Color(255, 255, 255));
        rechercher.setText("RECHERCHER");
        rechercher.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });
        jPanel1.add(rechercher);
        rechercher.setBounds(740, 130, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrenomActionPerformed

    private void textPrenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPrenomKeyReleased
        // TODO add your handling code here:
        // tableRecherche(textPrenom.getText());
    }//GEN-LAST:event_textPrenomKeyReleased

    private void textNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomActionPerformed

    private void textMatiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMatiereActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMatiereActionPerformed

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        // TODO add your handling code here:
        connexion conn = new connexion();
       // long p = 0;
        String s="";
        String login = login();
        try{
            pst = conn.con.prepareStatement("insert into enseignant(prenomEns,nomEns,codeMat,loginEns)values(?,?,?,?)");
            pst.setString(1,textPrenom.getText());
            pst.setString(2,textNom.getText());
            pst.setString(3,textMatiere.getText());
            pst.setString(4,login);
         //   pst.setString(5,login);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Enseignant ajoute!");
            //mettre a jour le tableau avec les donnees ajouter
             tableauEnseignant();
            pst.close();
            textPrenom.setText(s);
            textNom.setText(s);
            textMatiere.setText(s);
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"ECHEC!",null,JOptionPane.ERROR_MESSAGE);
         
        }
    }//GEN-LAST:event_enregistrerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        connexion conn = new connexion();
        String s="";
        // String intitule= textIntitule.getText();
        try{

            pst = conn.con.prepareStatement("update enseignant set prenomEns=?,nomEns=?,codeMat=? where prenomEns=?");
            pst.setString(4,textPrenom.getText());
              pst.setString(1,textPrenom.getText());
            pst.setString(2,textNom.getText());
            pst.setString(3,textMatiere.getText());
           
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, " valeur modifer!");
            pst.close();
            tableauEnseignant();
            textPrenom.setText(s);
            textNom.setText(s);
            textMatiere.setText(s);

        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"ECHEC!",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modifierActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        // TODO add your handling code here:
        acceuilleAdmin pageAdmin = new acceuilleAdmin();
        pageAdmin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_retourActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        int selectionner= jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        textPrenom.setText(model.getValueAt(selectionner, 1).toString());
        textNom.setText(model.getValueAt(selectionner, 2).toString());
        textMatiere.setText(model.getValueAt(selectionner,3).toString());
    }//GEN-LAST:event_jTable1MouseReleased

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        String s="";
        int option= JOptionPane.showConfirmDialog(null, "voulez vous supprimer l'enseignant","supression",JOptionPane.YES_NO_OPTION);
        connexion conn = new connexion();
        if(option==0){
            try{
                pst = conn.con.prepareStatement("delete from enseignant where prenomEns=?");
                pst.setString(1,textPrenom.getText());
                pst.executeUpdate();
                pst.close();
                tableauEnseignant();
                JOptionPane.showMessageDialog(this, " enseignant suprimer!");
                textPrenom.setText(s);
                textNom.setText(s);
                textMatiere.setText(s);

            }catch(Exception e){
                JOptionPane.showMessageDialog(null,"ECHEC!",null,JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_supprimerActionPerformed

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
        tableRecherche(textPrenom.getText(),textNom.getText());
    }//GEN-LAST:event_rechercherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouterEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouterEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouterEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouterEnseignant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouterEnseignant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel codeMatiere;
    private javax.swing.JButton enregistrer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifier;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel prenom;
    private javax.swing.JButton rechercher;
    private javax.swing.JButton retour;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField textMatiere;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textPrenom;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables

    private void tableauEnseignant() {
      connexion connect = new connexion();
        String colonne[] ={"MATRICULE","PRENOM","NOM","MATIERE","LOGIN"};
        DefaultTableModel model = new DefaultTableModel(null,colonne) ;
        PreparedStatement st ;
        ResultSet RS;
        try{
            st = connect.con.prepareStatement("SELECT enseignant.*, matiere.nomMat FROM enseignant INNER JOIN matiere ON enseignant.codeMat = matiere.codeMat");
           RS= st.executeQuery();
           while(RS.next()){
               Object o[]= {
                    RS.getString("matriculeEns"),
                   RS.getString("prenomEns"),
                   RS.getString("nomEns"),
                   RS.getString("nomMat"),
                   RS.getString("loginEns")
               };
                model.addRow(o);
           };
          
           jTable1.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    // function login
     public String login(){
        String prenom = textPrenom.getText();
        String nom = textNom.getText();
        String loginEtu = prenom+nom+"@"+"univ-thies.sn";
        return loginEtu;
    }

    private void tableRecherche(String text, String text0) {
             connexion connect = new connexion();
        String colonne[] ={"MATRICULE","PRENOM","NOM","MATIERE","LOGIN"};
        DefaultTableModel model = new DefaultTableModel(null,colonne) ;
        PreparedStatement st ;
        ResultSet RS;
        try{
            st = connect.con.prepareStatement("SELECT enseignant.*, matiere.nomMat FROM enseignant INNER JOIN matiere ON enseignant.codeMAt = matiere.codeMat where prenomEns like'%"+text+"%' and nomEns like'%"+text0+"%'");
           RS= st.executeQuery();
           while(RS.next()){
               Object o[]= {
                    RS.getString("matriculeEns"),
                   RS.getString("prenomEns"),
                   RS.getString("nomEns"),
                   RS.getString("nomMat"),
                   RS.getString("loginEns")
                   
               };
                model.addRow(o);
           };
          
           jTable1.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
}
