/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;
import java.sql.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LATYR
 */
public class ajouterEtudiant extends javax.swing.JFrame {

    PreparedStatement pst;
    ResultSet rs;
    /**
     * Creates new form ajouterEtudiant
     */
    public ajouterEtudiant() {
        initComponents();
        tableauEtudiant();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textPrenom = new javax.swing.JTextField();
        titre = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        textNom = new javax.swing.JTextField();
        nom = new javax.swing.JLabel();
        textDateDeNaissance = new javax.swing.JTextField();
        dateDeNaissance = new javax.swing.JLabel();
        rechercher = new javax.swing.JButton();
        enregistrer = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        retour = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        supprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 40));
        setPreferredSize(new java.awt.Dimension(940, 700));

        jPanel1.setBackground(new java.awt.Color(119, 181, 254));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 500));
        jPanel1.setLayout(null);

        textPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrenomActionPerformed(evt);
            }
        });
        textPrenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textPrenomKeyReleased(evt);
            }
        });
        jPanel1.add(textPrenom);
        textPrenom.setBounds(320, 130, 210, 30);

        titre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(255, 255, 255));
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("GESTION DES ETUDIANTS");
        titre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true));
        jPanel1.add(titre);
        titre.setBounds(200, 10, 460, 60);

        prenom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        prenom.setForeground(new java.awt.Color(255, 255, 255));
        prenom.setText("PRENOM:");
        jPanel1.add(prenom);
        prenom.setBounds(200, 130, 100, 30);

        textNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomActionPerformed(evt);
            }
        });
        jPanel1.add(textNom);
        textNom.setBounds(320, 180, 210, 30);

        nom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.setText("NOM:");
        jPanel1.add(nom);
        nom.setBounds(240, 180, 70, 30);

        textDateDeNaissance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDateDeNaissanceActionPerformed(evt);
            }
        });
        jPanel1.add(textDateDeNaissance);
        textDateDeNaissance.setBounds(320, 240, 210, 30);

        dateDeNaissance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dateDeNaissance.setForeground(new java.awt.Color(255, 255, 255));
        dateDeNaissance.setText("DATE DE NAISSANCE:");
        jPanel1.add(dateDeNaissance);
        dateDeNaissance.setBounds(100, 240, 200, 30);

        rechercher.setBackground(new java.awt.Color(0, 153, 153));
        rechercher.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rechercher.setForeground(new java.awt.Color(255, 255, 255));
        rechercher.setText("RECHERCHER");
        rechercher.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });
        jPanel1.add(rechercher);
        rechercher.setBounds(580, 130, 160, 40);

        enregistrer.setBackground(new java.awt.Color(0, 153, 153));
        enregistrer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        enregistrer.setForeground(new java.awt.Color(255, 255, 255));
        enregistrer.setText("ENREGISTRER");
        enregistrer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });
        jPanel1.add(enregistrer);
        enregistrer.setBounds(70, 320, 160, 40);

        modifier.setBackground(new java.awt.Color(0, 153, 153));
        modifier.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        modifier.setForeground(new java.awt.Color(255, 255, 255));
        modifier.setText("MODIFIER");
        modifier.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        jPanel1.add(modifier);
        modifier.setBounds(280, 320, 160, 40);

        retour.setBackground(new java.awt.Color(0, 153, 153));
        retour.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        retour.setForeground(new java.awt.Color(255, 255, 255));
        retour.setText("HOME");
        retour.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        jPanel1.add(retour);
        retour.setBounds(700, 320, 160, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 400, 930, 240);

        supprimer.setBackground(new java.awt.Color(0, 153, 153));
        supprimer.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        supprimer.setForeground(new java.awt.Color(255, 255, 255));
        supprimer.setText("SUPPRIMER");
        supprimer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        jPanel1.add(supprimer);
        supprimer.setBounds(490, 320, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1196, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrenomActionPerformed

    private void textNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomActionPerformed

    private void textDateDeNaissanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDateDeNaissanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDateDeNaissanceActionPerformed

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        // TODO add your handling code here:
     tableRecherche(textPrenom.getText(),textNom.getText());
    }//GEN-LAST:event_rechercherActionPerformed

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        // TODO add your handling code here:
        String login = login();
         connexion conn = new connexion();
         String s="";
       try{
            pst = conn.con.prepareStatement("insert into etudiant(prenomEtu,nomEtu,dateNaiss,login)values(?,?,?,?)");
            pst.setString(1,textPrenom.getText());
            pst.setString(2,textNom.getText());
            pst.setString(3,textDateDeNaissance.getText());
             pst.setString(4,login);
             pst.executeUpdate();
            tableauEtudiant();
            JOptionPane.showMessageDialog(this, "Etudiant ajoute!");
            pst.close();
            textPrenom.setText(s);
            textNom.setText(s);
            textDateDeNaissance.setText(s);
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,"ECHEC!",null,JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_enregistrerActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
        // TODO add your handling code here:
        connexion conn = new connexion();
        String s="";
       String login = login();
       try{ 
           
            pst = conn.con.prepareStatement("update etudiant set nomEtu=?,dateNaiss=?,login = ? where prenomEtu=?");
            pst.setString(4,textPrenom.getText());
            pst.setString(1,textNom.getText());
            pst.setString(2,textDateDeNaissance.getText());
            pst.setString(3,login);
           //  pst.setString(4,textPrenom.getText());
             pst.executeUpdate();
            JOptionPane.showMessageDialog(this, " valeur modifer!");
            pst.close();
             tableauEtudiant();
            textPrenom.setText(s);
            textNom.setText(s);
            textDateDeNaissance.setText(s);
           
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null,"ECHEC!",null,JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_modifierActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        // TODO add your handling code here:
        acceuilleAdmin pageAdmin = new acceuilleAdmin();
        pageAdmin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_retourActionPerformed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        // TODO add your handling code here:
        int selectionner= jTable1.getSelectedRow();
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
          textPrenom.setText(model.getValueAt(selectionner, 1).toString());
          textNom.setText(model.getValueAt(selectionner, 2).toString());
          textDateDeNaissance.setText(model.getValueAt(selectionner,3).toString());
          
    }//GEN-LAST:event_jTable1MouseReleased

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
        // TODO add your handling code here:
        int option= JOptionPane.showConfirmDialog(null, "voulez vous supprimer cette etudiant","supression",JOptionPane.YES_NO_OPTION);
         connexion conn = new connexion();
         if(option==0){
            try{
                 pst = conn.con.prepareStatement("delete from etudiant where prenomEtu=?");
                  pst.setString(1,textPrenom.getText());
                  pst.executeUpdate();
                  pst.close();
                  tableauEtudiant();
                  JOptionPane.showMessageDialog(this, " Etudiant suprimer!");
            }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"ECHEC!",null,JOptionPane.ERROR_MESSAGE);
            }
         }
    }//GEN-LAST:event_supprimerActionPerformed

    private void textPrenomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPrenomKeyReleased
        // TODO add your handling code here:
       // tableRecherche(textPrenom.getText());
    }//GEN-LAST:event_textPrenomKeyReleased

    // cette methode creer un login pour l'etudiant
    public String login(){
        String prenom = textPrenom.getText();
        String nom = textNom.getText();
        String loginEtu = prenom+nom+"@"+"univ-thies.sn";
        return loginEtu;
    }
    //tableau etudiant
     private void tableauEtudiant(){
        connexion connect = new connexion();
        String colonne[] ={"INE","prenom","nom","dateNaissance","login"};
        DefaultTableModel model = new DefaultTableModel(null,colonne) ;
        PreparedStatement st ;
        ResultSet RS;
        try{
            st = connect.con.prepareStatement("select* from Etudiant");
           RS= st.executeQuery();
           while(RS.next()){
               Object o[]= {
                    RS.getString("INE"),
                   RS.getString("prenomEtu"),
                   RS.getString("nomEtu"),
                   RS.getString("dateNaiss"),
                   RS.getString("login")
                //RS.getInt("note")
               };
                model.addRow(o);
           };
          
           jTable1.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajouterEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajouterEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajouterEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajouterEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajouterEtudiant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateDeNaissance;
    private javax.swing.JButton enregistrer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifier;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel prenom;
    private javax.swing.JButton rechercher;
    private javax.swing.JButton retour;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField textDateDeNaissance;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textPrenom;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables

    private void tableRecherche(String text, String text1) {
       connexion connect = new connexion();
        String colonne[] ={"INE","prenom","nom","dateNaissance","login"};
        DefaultTableModel model = new DefaultTableModel(null,colonne) ;
        PreparedStatement st ;
        ResultSet RS;
        try{
            st = connect.con.prepareStatement("select* from Etudiant where prenomEtu like'%"+text+"%' and nomEtu like'%"+text1+"%'");
           RS= st.executeQuery();
           while(RS.next()){
               Object o[]= {
                    RS.getString("INE"),
                   RS.getString("prenomEtu"),
                   RS.getString("nomEtu"),
                   RS.getString("dateNaiss"),
                   RS.getString("login")
                //RS.getInt("note")
               };
                model.addRow(o);
           };
          
           jTable1.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
}
