/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;

import java.sql.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
public class connectionAdmin extends javax.swing.JFrame {

   PreparedStatement pst;
   
   ResultSet rs;
  
    public connectionAdmin() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        retour = new javax.swing.JButton();
        matricule = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        textMotDePasse = new javax.swing.JTextField();
        textLogin = new javax.swing.JTextField();
        seConnecter = new javax.swing.JButton();
        titre = new javax.swing.JLabel();
        ErroMotDePasse = new javax.swing.JLabel();
        ErrorLogin = new javax.swing.JLabel();
        messageError = new javax.swing.JLabel();
        font = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 90));
        setMinimumSize(new java.awt.Dimension(623, 590));
        getContentPane().setLayout(null);

        retour.setBackground(new java.awt.Color(0, 135, 135));
        retour.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        retour.setForeground(new java.awt.Color(255, 255, 255));
        retour.setText("RETOUR");
        retour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(80, 410, 170, 40);

        matricule.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        matricule.setText("MOT DE PASSE:");
        getContentPane().add(matricule);
        matricule.setBounds(150, 290, 140, 30);

        login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        login.setText("LOGIN:");
        getContentPane().add(login);
        login.setBounds(220, 220, 65, 30);

        textMotDePasse.setBackground(new java.awt.Color(0, 135, 204));
        textMotDePasse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textMotDePasse.setForeground(new java.awt.Color(255, 255, 255));
        textMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMotDePasseActionPerformed(evt);
            }
        });
        getContentPane().add(textMotDePasse);
        textMotDePasse.setBounds(300, 290, 240, 30);

        textLogin.setBackground(new java.awt.Color(0, 135, 204));
        textLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textLogin.setForeground(new java.awt.Color(255, 255, 255));
        textLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLoginActionPerformed(evt);
            }
        });
        getContentPane().add(textLogin);
        textLogin.setBounds(300, 220, 240, 30);

        seConnecter.setBackground(new java.awt.Color(0, 135, 135));
        seConnecter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        seConnecter.setForeground(new java.awt.Color(255, 255, 255));
        seConnecter.setText("SE CONNECTER");
        seConnecter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        seConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seConnecterActionPerformed(evt);
            }
        });
        getContentPane().add(seConnecter);
        seConnecter.setBounds(360, 410, 170, 40);

        titre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText(" ADMIN LOGIN PAGE");
        getContentPane().add(titre);
        titre.setBounds(195, 80, 350, 21);

        ErroMotDePasse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ErroMotDePasse.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErroMotDePasse);
        ErroMotDePasse.setBounds(300, 320, 260, 30);

        ErrorLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ErrorLogin.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(ErrorLogin);
        ErrorLogin.setBounds(300, 250, 260, 30);

        messageError.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        messageError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(messageError);
        messageError.setBounds(227, 350, 320, 40);

        font.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login2.jpg"))); // NOI18N
        getContentPane().add(font);
        font.setBounds(0, 0, 623, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMotDePasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMotDePasseActionPerformed

    private void textLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLoginActionPerformed

    private void seConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seConnecterActionPerformed
        // TODO add your handling code here:
         String login= textLogin.getText();
         String MotDePasse= textMotDePasse.getText();
            try{
                if(login.isEmpty() || MotDePasse.isEmpty()){
                    ErroMotDePasse.setText("champ vide!");
                    ErrorLogin.setText("champ vide!");
                    messageError.setText("veuillez remplir les champs"); 
                    JOptionPane.showMessageDialog(null,"ECHEC! connexion",null,JOptionPane.ERROR_MESSAGE);
                }
                else{
                 connexion conect = new connexion();//  connection a la base de donnee
                         pst = conect.con.prepareStatement("select * from chefDepart where login =? and motDePasse=?");
                         pst.setString(1, login);
                         pst.setString(2, MotDePasse);
                         rs=pst.executeQuery();
                         if(!rs.isBeforeFirst()){//donnees existe pas
                             messageError.setText("ce compte n'existe pas");
                             ErrorLogin.setText("");
                             ErroMotDePasse.setText("");
                             if(login!="admin" ){
                             // messageError.setText("c'est un professeur");
                            // pst1 = conect.con.prepareStatement("select * from enseignant");
                              
                     //       rs.getString(1 );
                         }
                         }
                         
                         else{// si les donnees sont dans la bases de donnes 
                             while(rs.next()){
                               // login.super.dispose();
                                messageError.setText("connection reussi");
                                acceuilleAdmin pageAcceuil = new acceuilleAdmin();
                                
                                    pageAcceuil.setVisible(true);
                                    setVisible(false);
                                
                             }
                        }
                      }
            }
            catch(Exception e){
                    
                    }
             
    }//GEN-LAST:event_seConnecterActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        
        //retour a la page seConnecter
        SeConnecter seConnecter = new SeConnecter();
        seConnecter.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(connectionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(connectionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(connectionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(connectionAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new connectionAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErroMotDePasse;
    private javax.swing.JLabel ErrorLogin;
    private javax.swing.JLabel font;
    private javax.swing.JLabel login;
    private javax.swing.JLabel matricule;
    private javax.swing.JLabel messageError;
    private javax.swing.JButton retour;
    private javax.swing.JButton seConnecter;
    private javax.swing.JTextField textLogin;
    private javax.swing.JTextField textMotDePasse;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
