/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;

import java.sql.*;
import javax.swing.JOptionPane;


public class connectionProffesseur extends javax.swing.JFrame {
    // String LOGIN = TextLogin.getText();

     PreparedStatement pst;
      ResultSet rs;
    public connectionProffesseur() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titre = new javax.swing.JLabel();
        MotDePasse = new javax.swing.JLabel();
        TextMotDePasse = new javax.swing.JTextField();
        login = new javax.swing.JLabel();
        TextLogin = new javax.swing.JTextField();
        RETOUR = new javax.swing.JButton();
        SECONNECTER = new javax.swing.JButton();
        messageError = new javax.swing.JLabel();
        font = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 90));
        setMinimumSize(new java.awt.Dimension(645, 585));
        getContentPane().setLayout(null);

        titre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("TEACHERS LOGIN PAGE");
        getContentPane().add(titre);
        titre.setBounds(200, 80, 350, 20);

        MotDePasse.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MotDePasse.setText("MOT DE PASSE:");
        getContentPane().add(MotDePasse);
        MotDePasse.setBounds(110, 290, 140, 40);

        TextMotDePasse.setBackground(new java.awt.Color(0, 135, 135));
        TextMotDePasse.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextMotDePasse.setForeground(new java.awt.Color(255, 255, 255));
        TextMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextMotDePasseActionPerformed(evt);
            }
        });
        getContentPane().add(TextMotDePasse);
        TextMotDePasse.setBounds(260, 290, 230, 30);

        login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        login.setText("LOGIN:");
        getContentPane().add(login);
        login.setBounds(180, 210, 130, 40);

        TextLogin.setBackground(new java.awt.Color(0, 135, 135));
        TextLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TextLogin.setForeground(new java.awt.Color(255, 255, 255));
        TextLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextLoginActionPerformed(evt);
            }
        });
        getContentPane().add(TextLogin);
        TextLogin.setBounds(260, 210, 230, 30);

        RETOUR.setBackground(new java.awt.Color(0, 153, 204));
        RETOUR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        RETOUR.setForeground(new java.awt.Color(255, 255, 255));
        RETOUR.setText("RETOUR");
        RETOUR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        RETOUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETOURActionPerformed(evt);
            }
        });
        getContentPane().add(RETOUR);
        RETOUR.setBounds(100, 390, 180, 40);

        SECONNECTER.setBackground(new java.awt.Color(0, 153, 204));
        SECONNECTER.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SECONNECTER.setForeground(new java.awt.Color(255, 255, 255));
        SECONNECTER.setText("SE CONNECTER");
        SECONNECTER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        SECONNECTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SECONNECTERActionPerformed(evt);
            }
        });
        getContentPane().add(SECONNECTER);
        SECONNECTER.setBounds(360, 390, 180, 40);

        messageError.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        messageError.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(messageError);
        messageError.setBounds(200, 320, 310, 40);

        font.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login2.jpg"))); // NOI18N
        getContentPane().add(font);
        font.setBounds(0, 0, 630, 565);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextMotDePasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextMotDePasseActionPerformed

    private void TextLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextLoginActionPerformed

    private void RETOURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETOURActionPerformed
        // TODO add your handling code here:
        // retour a la page de connection
        SeConnecter SeConect = new SeConnecter();
        SeConect.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_RETOURActionPerformed

    private void SECONNECTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SECONNECTERActionPerformed
        // TODO add your handling code here:
        String login = TextLogin.getText();
        String motDePasse = TextMotDePasse.getText();
        
        try{
            if(login.isEmpty() || motDePasse.isEmpty()){
           JOptionPane.showMessageDialog(null,"ECHEC! connexion",null,JOptionPane.ERROR_MESSAGE);
           messageError.setText("veuillez remplir les champ!");

            }else{
                 connexion conect = new connexion();//  connection a la base de donnee
                         pst = conect.con.prepareStatement("select * from enseignant where loginEns =? and matriculeEns=?");
                         pst.setString(1, TextLogin.getText());
                         pst.setString(2, motDePasse);
                         rs=pst.executeQuery();
                         if(!rs.isBeforeFirst()){ //si les informations ne figurent pas dans la base de donne
                             JOptionPane.showMessageDialog(null,"ce compte n'existe pas!",null,JOptionPane.ERROR_MESSAGE);
                         }else{// si les donnees sont dans la bases de donnes 
                             while(rs.next()){
                               // login.super.dispose();
                           
                                AcceuilEnseignant pageAcceuil = new AcceuilEnseignant();
                                
                                    pageAcceuil.setVisible(true);
                                    setVisible(false);
                                
                             }
                        }
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_SECONNECTERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(connectionProffesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(connectionProffesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(connectionProffesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(connectionProffesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new connectionProffesseur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MotDePasse;
    private javax.swing.JButton RETOUR;
    private javax.swing.JButton SECONNECTER;
    private javax.swing.JTextField TextLogin;
    private javax.swing.JTextField TextMotDePasse;
    private javax.swing.JLabel font;
    private javax.swing.JLabel login;
    private javax.swing.JLabel messageError;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
