/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;

import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author LATYR
 */
public class deliberation extends javax.swing.JFrame {

    /**
     * Creates new form deliberation
     */
    public deliberation() {
        initComponents();
        tabEtuValide();
        tabEtuRatra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acceuilleAdmin = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        titre1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRattrap = new javax.swing.JTable();
        titre2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablevalide = new javax.swing.JTable();
        retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 40));
        setMinimumSize(new java.awt.Dimension(1000, 1000));

        acceuilleAdmin.setBackground(new java.awt.Color(0, 153, 153));
        acceuilleAdmin.setLayout(null);

        titre.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(255, 255, 255));
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("LISTES DES ETUDIANTS N'AYANT PAS VALIDE ");
        titre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        acceuilleAdmin.add(titre);
        titre.setBounds(50, 330, 930, 30);

        prenom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        prenom.setForeground(new java.awt.Color(255, 255, 255));
        acceuilleAdmin.add(prenom);
        prenom.setBounds(-40, 30, 100, 40);

        titre1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titre1.setForeground(new java.awt.Color(255, 255, 255));
        titre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre1.setText("DELIBERATION");
        titre1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 4, true));
        acceuilleAdmin.add(titre1);
        titre1.setBounds(300, 10, 460, 50);

        jTableRattrap.setForeground(new java.awt.Color(255, 0, 0));
        jTableRattrap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRattrap);

        acceuilleAdmin.add(jScrollPane1);
        jScrollPane1.setBounds(80, 380, 880, 200);

        titre2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titre2.setForeground(new java.awt.Color(255, 255, 255));
        titre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre2.setText("LISTES DES ETUDIANTS AYANT VALIDE PAR ORDRE DE MERITE");
        titre2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        acceuilleAdmin.add(titre2);
        titre2.setBounds(50, 70, 930, 33);

        jTablevalide.setForeground(new java.awt.Color(0, 102, 0));
        jTablevalide.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTablevalide);

        acceuilleAdmin.add(jScrollPane2);
        jScrollPane2.setBounds(80, 120, 870, 190);

        retour.setBackground(new java.awt.Color(119, 181, 204));
        retour.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        retour.setText("HOME");
        retour.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        acceuilleAdmin.add(retour);
        retour.setBounds(810, 590, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 986, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(acceuilleAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(acceuilleAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        // TODO add your handling code here:
        acceuilleAdmin pageAdmin = new acceuilleAdmin();
        pageAdmin.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deliberation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deliberation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deliberation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deliberation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deliberation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acceuilleAdmin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRattrap;
    private javax.swing.JTable jTablevalide;
    private javax.swing.JLabel prenom;
    private javax.swing.JButton retour;
    private javax.swing.JLabel titre;
    private javax.swing.JLabel titre1;
    private javax.swing.JLabel titre2;
    // End of variables declaration//GEN-END:variables

    private void tabEtuValide() {
            connexion connect = new connexion();
        String colonne[] ={"INE","PRENOM","NOM","MOYENNE","CREDIT"};
        DefaultTableModel model = new DefaultTableModel(null,colonne) ;
        PreparedStatement st ;
        ResultSet RS;
        try{
            st = connect.con.prepareStatement("SELECT e.nomEtu, e.prenomEtu, n.INEETU, n.note, m.nomMat, AVG(n.note) as moyenne, SUM(n.credit) as totalCredit\n" +
"FROM etudiant e \n" +
"INNER JOIN notes n ON e.INE = n.INEETU\n" +
"INNER JOIN matiere m ON n.codeMat = m.codeMat\n" +
"GROUP BY n.INEETU \n" +
"HAVING SUM(n.credit) = 30 ORDER BY moyenne DESC");
           RS= st.executeQuery();
           while(RS.next()){
               Object o[]= {
                    RS.getString("INEETU"),
                  // RS.getString("moyenne"),
                   RS.getString("prenomEtu"),
                   RS.getString("nomEtu"),
                    RS.getString("moyenne"),
                   RS.getString("totalCredit"),
                  // RS.getString("nomMat"),
                   
                 //  RS.getString("login")
                //RS.getInt("note")
               };
                model.addRow(o);
           };
          
           jTablevalide.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    private void tabEtuRatra() {
                  connexion connect = new connexion();
        String colonne[] ={"INE","PRENOM","NOM","MOYENNE","CREDIT"};
        DefaultTableModel model = new DefaultTableModel(null,colonne) ;
        PreparedStatement st ;
        ResultSet RS;
        try{
            st = connect.con.prepareStatement("SELECT e.nomEtu, e.prenomEtu, n.INEETU, n.note, m.nomMat, AVG(n.note) as moyenne, SUM(n.credit) as totalCredit\n" +
"FROM etudiant e \n" +
"INNER JOIN notes n ON e.INE = n.INEETU\n" +
"INNER JOIN matiere m ON n.codeMat = m.codeMat\n" +
"GROUP BY n.INEETU \n" +
"HAVING SUM(n.credit) < 30 ORDER BY moyenne DESC");
           RS= st.executeQuery();
           while(RS.next()){
               Object o[]= {
                    RS.getString("INEETU"),
                  // RS.getString("moyenne"),
                   RS.getString("prenomEtu"),
                   RS.getString("nomEtu"),
                    RS.getString("moyenne"),
                   RS.getString("totalCredit"),
                 //  RS.getString("nomMat"),
                   
                 //  RS.getString("login")
                //RS.getInt("note")
               };
                model.addRow(o);
           };
          
           jTableRattrap.setModel(model);
        }catch(Exception e){
            e.printStackTrace();
        }
          
    }
}
