/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;

import java.sql.*;

public class inscription extends javax.swing.JFrame {

   PreparedStatement pst ;
   ResultSet rs;
    public inscription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INE = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        INE1 = new javax.swing.JLabel();
        mtdepass = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        confirmerMDpass = new javax.swing.JLabel();
        textPrenom = new javax.swing.JTextField();
        textNom = new javax.swing.JTextField();
        textMOTDPASS = new javax.swing.JTextField();
        retour = new javax.swing.JButton();
        inscription = new javax.swing.JButton();
        textmotDePasse = new javax.swing.JPasswordField();
        textConfirmemotDePasse = new javax.swing.JPasswordField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        dateDeNaissance = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        font = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setMinimumSize(new java.awt.Dimension(623, 590));
        getContentPane().setLayout(null);

        INE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        INE.setText("CONFIRMER MOT DE PASSE:");
        getContentPane().add(INE);
        INE.setBounds(10, 370, 270, 30);

        prenom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        prenom.setText("INE:");
        getContentPane().add(prenom);
        prenom.setBounds(230, 160, 70, 30);

        INE1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        INE1.setText("PRENOM:");
        getContentPane().add(INE1);
        INE1.setBounds(180, 200, 140, 30);

        mtdepass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mtdepass.setText("NOM:");
        getContentPane().add(mtdepass);
        mtdepass.setBounds(220, 250, 70, 30);

        titre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titre.setForeground(new java.awt.Color(51, 51, 51));
        titre.setText("INSCRIPTION");
        getContentPane().add(titre);
        titre.setBounds(300, 50, 240, 50);

        confirmerMDpass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        confirmerMDpass.setText("MOT DE PASSE:");
        getContentPane().add(confirmerMDpass);
        confirmerMDpass.setBounds(130, 330, 140, 30);

        textPrenom.setBackground(new java.awt.Color(0, 153, 153));
        textPrenom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        textPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrenomActionPerformed(evt);
            }
        });
        getContentPane().add(textPrenom);
        textPrenom.setBounds(280, 160, 220, 30);

        textNom.setBackground(new java.awt.Color(0, 153, 153));
        textNom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        textNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomActionPerformed(evt);
            }
        });
        getContentPane().add(textNom);
        textNom.setBounds(280, 200, 220, 30);

        textMOTDPASS.setBackground(new java.awt.Color(0, 153, 153));
        textMOTDPASS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        textMOTDPASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMOTDPASSActionPerformed(evt);
            }
        });
        getContentPane().add(textMOTDPASS);
        textMOTDPASS.setBounds(280, 250, 220, 30);

        retour.setBackground(new java.awt.Color(0, 135, 204));
        retour.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        retour.setForeground(new java.awt.Color(255, 255, 255));
        retour.setText("RETOUR");
        retour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        getContentPane().add(retour);
        retour.setBounds(80, 450, 190, 50);

        inscription.setBackground(new java.awt.Color(0, 135, 204));
        inscription.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        inscription.setForeground(new java.awt.Color(255, 255, 255));
        inscription.setText("S'INSCRIRE");
        inscription.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        inscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscriptionActionPerformed(evt);
            }
        });
        getContentPane().add(inscription);
        inscription.setBounds(400, 450, 190, 50);

        textmotDePasse.setBackground(new java.awt.Color(0, 135, 135));
        textmotDePasse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        getContentPane().add(textmotDePasse);
        textmotDePasse.setBounds(280, 330, 220, 30);

        textConfirmemotDePasse.setBackground(new java.awt.Color(0, 135, 135));
        textConfirmemotDePasse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(135, 135, 135), 2));
        getContentPane().add(textConfirmemotDePasse);
        textConfirmemotDePasse.setBounds(280, 370, 220, 30);

        jDateChooser1.setBackground(new java.awt.Color(0, 153, 153));
        jDateChooser1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(280, 290, 220, 30);

        dateDeNaissance.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dateDeNaissance.setText("DATE DE NAISSANCE:");
        getContentPane().add(dateDeNaissance);
        dateDeNaissance.setBounds(80, 290, 190, 30);

        message.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        message.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(message);
        message.setBounds(250, 410, 280, 30);

        font.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login2.jpg"))); // NOI18N
        getContentPane().add(font);
        font.setBounds(0, -30, 623, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrenomActionPerformed

    private void textNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomActionPerformed

    private void textMOTDPASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMOTDPASSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMOTDPASSActionPerformed

    private void inscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscriptionActionPerformed
        // TODO add your handling code here:
//        try{
//            connexion conect = new connexion();
//            pst=conect.con.prepareStatement("insert into Etudiant (PrenomEtu,nomEtu,dateNaiss)values(?,?,?)");
//            pst.setString(1, textPrenom.getText());
//             pst.setString(2, textNom.getText());
//            
//        }catch( Exception e){
//        }
    }//GEN-LAST:event_inscriptionActionPerformed

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        
        welcomePage acceuille = new welcomePage();
        acceuille.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_retourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel INE;
    private javax.swing.JLabel INE1;
    private javax.swing.JLabel confirmerMDpass;
    private javax.swing.JLabel dateDeNaissance;
    private javax.swing.JLabel font;
    private javax.swing.JButton inscription;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel mtdepass;
    private javax.swing.JLabel prenom;
    private javax.swing.JButton retour;
    private javax.swing.JPasswordField textConfirmemotDePasse;
    private javax.swing.JTextField textMOTDPASS;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textPrenom;
    private javax.swing.JPasswordField textmotDePasse;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
