/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;

import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.*;
/**
 *
 * @author LATYR
 */
public class modifierPhoto extends javax.swing.JFrame {

   String s;
PreparedStatement pst;
ResultSet rs;
    public modifierPhoto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        ajouter = new javax.swing.JButton();
        parcourir = new javax.swing.JButton();
        retour = new javax.swing.JButton();
        enregistrer = new javax.swing.JButton();
        Prenom = new javax.swing.JLabel();
        textLogin = new javax.swing.JTextField();
        nom = new javax.swing.JLabel();
        textNomDep = new javax.swing.JTextField();
        matricule = new javax.swing.JLabel();
        textMatricule = new javax.swing.JTextField();
        Prenom1 = new javax.swing.JLabel();
        textMotDePasse = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(180, 50));

        jPanel1.setBackground(new java.awt.Color(119, 181, 254));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(null);

        titre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("MODIFICATION PROFIL");
        titre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 4, true));
        jPanel1.add(titre);
        titre.setBounds(390, 10, 372, 46);

        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));
        jPanel1.add(photo);
        photo.setBounds(44, 88, 145, 149);

        ajouter.setBackground(new java.awt.Color(0, 153, 153));
        ajouter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ajouter.setForeground(new java.awt.Color(255, 255, 255));
        ajouter.setText("AJOUTER");
        ajouter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel1.add(ajouter);
        ajouter.setBounds(30, 370, 134, 37);

        parcourir.setBackground(new java.awt.Color(0, 153, 153));
        parcourir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        parcourir.setForeground(new java.awt.Color(255, 255, 255));
        parcourir.setText("PARCOURIR");
        parcourir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parcourirActionPerformed(evt);
            }
        });
        jPanel1.add(parcourir);
        parcourir.setBounds(30, 310, 134, 37);

        retour.setBackground(new java.awt.Color(0, 153, 153));
        retour.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        retour.setForeground(new java.awt.Color(255, 255, 255));
        retour.setText("RETOUR");
        retour.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        jPanel1.add(retour);
        retour.setBounds(380, 290, 134, 37);

        enregistrer.setBackground(new java.awt.Color(0, 153, 153));
        enregistrer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enregistrer.setForeground(new java.awt.Color(255, 255, 255));
        enregistrer.setText("ENREGISTRER");
        enregistrer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 3, true));
        enregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerActionPerformed(evt);
            }
        });
        jPanel1.add(enregistrer);
        enregistrer.setBounds(610, 290, 134, 37);

        Prenom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Prenom.setText("LOGIN:");
        jPanel1.add(Prenom);
        Prenom.setBounds(400, 180, 70, 29);

        textLogin.setBackground(new java.awt.Color(0, 153, 153));
        textLogin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textLogin.setForeground(new java.awt.Color(255, 255, 255));
        textLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        textLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLoginActionPerformed(evt);
            }
        });
        jPanel1.add(textLogin);
        textLogin.setBounds(480, 180, 230, 30);

        nom.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nom.setText("NOM_DEPART:");
        jPanel1.add(nom);
        nom.setBounds(340, 140, 130, 29);

        textNomDep.setBackground(new java.awt.Color(0, 153, 153));
        textNomDep.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textNomDep.setForeground(new java.awt.Color(255, 255, 255));
        textNomDep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        textNomDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomDepActionPerformed(evt);
            }
        });
        jPanel1.add(textNomDep);
        textNomDep.setBounds(480, 140, 230, 30);

        matricule.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        matricule.setText("MATRICULE:");
        jPanel1.add(matricule);
        matricule.setBounds(350, 100, 120, 29);

        textMatricule.setBackground(new java.awt.Color(0, 153, 153));
        textMatricule.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textMatricule.setForeground(new java.awt.Color(255, 255, 255));
        textMatricule.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        textMatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMatriculeActionPerformed(evt);
            }
        });
        jPanel1.add(textMatricule);
        textMatricule.setBounds(480, 100, 230, 30);

        Prenom1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Prenom1.setText("MOT DE PASSE:");
        jPanel1.add(Prenom1);
        Prenom1.setBounds(330, 220, 150, 29);

        textMotDePasse.setBackground(new java.awt.Color(0, 153, 153));
        textMotDePasse.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        textMotDePasse.setForeground(new java.awt.Color(255, 255, 255));
        textMotDePasse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 3));
        textMotDePasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMotDePasseActionPerformed(evt);
            }
        });
        jPanel1.add(textMotDePasse);
        textMotDePasse.setBounds(480, 220, 230, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
try{
				//Class.forName("com.mysql.jdbc.Driver");
				 connexion conect = new connexion();//  connection a la base de donnee
                         pst = conect.con.prepareStatement("update chefdepart set photo=?  where matricule_Cf_Dep=?");
			InputStream is=new FileInputStream(new File(s));
			pst.setBlob(1,is);
			pst.setString(2,textMatricule.getText());
			pst.executeUpdate();
                         if(!rs.isBeforeFirst()){
                             JOptionPane.showMessageDialog(null,"Matricule introuvable !",null,JOptionPane.ERROR_MESSAGE);
                         }else{
                             while(rs.next()){
                                 JOptionPane.showMessageDialog(null,"Data inserted!"); 
			           dispose();
                             }
                         }
			
			}
			catch(Exception ex){
				//ex.printStackTrace();
				JOptionPane.showMessageDialog(null,"sectionner d'abord un fichier!",null,JOptionPane.ERROR_MESSAGE); 
			}    }//GEN-LAST:event_ajouterActionPerformed

    private void parcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parcourirActionPerformed
       
        try{
            
            if(textMatricule.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"Saissez votre matricule d'abord !",null,JOptionPane.ERROR_MESSAGE); 
            }else{
                 JFileChooser fileChooser=new JFileChooser();
			fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
			FileNameExtensionFilter filter=new FileNameExtensionFilter("*.IMAGE","jpg","gif","png");
			fileChooser.addChoosableFileFilter(filter);
			int result=fileChooser.showSaveDialog(null);
			if(result==fileChooser.APPROVE_OPTION){
				File selectedFile=fileChooser.getSelectedFile();
				String path=selectedFile.getAbsolutePath();
				photo.setIcon(ResizeImage(path));
				 s=path;
			}
			else if(result==JFileChooser.CANCEL_OPTION){
				System.out.println("No data!");
			}
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"ECHEC !",null,JOptionPane.ERROR_MESSAGE); 
        }
          
    }//GEN-LAST:event_parcourirActionPerformed

    public ImageIcon ResizeImage(String imPath){
		ImageIcon myImage=new ImageIcon(imPath);
		Image img=myImage.getImage();
		Image  newImage=img.getScaledInstance(photo.getWidth(),photo.getHeight(),Image.SCALE_SMOOTH);
		ImageIcon image=new ImageIcon(newImage);
		return image;
		
	}
    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
        // TODO add your handling code here:
        acceuilleAdmin acceuille = new acceuilleAdmin();
        acceuille.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_retourActionPerformed

    private void enregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerActionPerformed
        // TODO add your handling code here:
        connexion conn = new connexion();
       // long p = 0;
        String s="";
       // String login = login();
        try{
            pst = conn.con.prepareStatement("update chefdepart set nomDep=?,login=?,motDePasse=? where matricule_Cf_Dep=?");
            pst.setString(4,textMatricule.getText());
              pst.setString(1,textNomDep.getText());
            pst.setString(2,textLogin.getText());
          
            pst.setString(3,textMotDePasse.getText());
        
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "informations modifés!");
            
            textLogin.setText(s);
            textNomDep.setText(s);
            textMotDePasse.setText(s);
            textMatricule.setText(s);
        }
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"ECHEC!",null,JOptionPane.ERROR_MESSAGE);
         
        }
         
    }//GEN-LAST:event_enregistrerActionPerformed

    private void textLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLoginActionPerformed

    private void textNomDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomDepActionPerformed

    private void textMatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMatriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMatriculeActionPerformed

    private void textMotDePasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMotDePasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMotDePasseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifierPhoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifierPhoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifierPhoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifierPhoto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifierPhoto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Prenom;
    private javax.swing.JLabel Prenom1;
    private javax.swing.JButton ajouter;
    private javax.swing.JButton enregistrer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel matricule;
    private javax.swing.JLabel nom;
    private javax.swing.JButton parcourir;
    private javax.swing.JLabel photo;
    private javax.swing.JButton retour;
    private javax.swing.JTextField textLogin;
    private javax.swing.JTextField textMatricule;
    private javax.swing.JTextField textMotDePasse;
    private javax.swing.JTextField textNomDep;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
