/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;

import java.sql.*;
import javax.swing.JOptionPane;
public class PageDeconnexion1 extends javax.swing.JFrame {

   PreparedStatement pst;
   ResultSet rs;
    public PageDeconnexion1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Retour = new javax.swing.JButton();
        MOTDEPASSE = new javax.swing.JLabel();
        INE = new javax.swing.JLabel();
        textLogin = new javax.swing.JTextField();
        titre = new javax.swing.JLabel();
        SEConnecter = new javax.swing.JButton();
        messageEror = new javax.swing.JLabel();
        errorLogin = new javax.swing.JLabel();
        errorINE = new javax.swing.JLabel();
        textINE = new javax.swing.JTextField();
        FONT = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(400, 90));
        setMinimumSize(new java.awt.Dimension(645, 590));
        getContentPane().setLayout(null);

        Retour.setBackground(new java.awt.Color(0, 153, 204));
        Retour.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Retour.setForeground(new java.awt.Color(255, 255, 255));
        Retour.setText("RETOUR");
        Retour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });
        getContentPane().add(Retour);
        Retour.setBounds(50, 440, 170, 40);

        MOTDEPASSE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        MOTDEPASSE.setForeground(new java.awt.Color(51, 51, 51));
        MOTDEPASSE.setText("LOGIN:");
        getContentPane().add(MOTDEPASSE);
        MOTDEPASSE.setBounds(110, 240, 150, 60);

        INE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        INE.setForeground(new java.awt.Color(51, 51, 51));
        INE.setText("INE :");
        getContentPane().add(INE);
        INE.setBounds(120, 300, 110, 60);

        textLogin.setBackground(new java.awt.Color(0, 135, 135));
        textLogin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textLogin.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textLogin);
        textLogin.setBounds(190, 250, 210, 30);

        titre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titre.setForeground(new java.awt.Color(51, 51, 51));
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("STUDENTS LOGIN PAGE");
        getContentPane().add(titre);
        titre.setBounds(200, 50, 350, 20);

        SEConnecter.setBackground(new java.awt.Color(0, 153, 204));
        SEConnecter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SEConnecter.setForeground(new java.awt.Color(255, 255, 255));
        SEConnecter.setText("SE CONNECTER");
        SEConnecter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        SEConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEConnecterActionPerformed(evt);
            }
        });
        getContentPane().add(SEConnecter);
        SEConnecter.setBounds(350, 440, 170, 40);

        messageEror.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        messageEror.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(messageEror);
        messageEror.setBounds(140, 370, 330, 30);

        errorLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        errorLogin.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errorLogin);
        errorLogin.setBounds(190, 280, 250, 20);

        errorINE.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        errorINE.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(errorINE);
        errorINE.setBounds(190, 350, 250, 20);

        textINE.setBackground(new java.awt.Color(0, 135, 135));
        textINE.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textINE.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textINE);
        textINE.setBounds(190, 320, 210, 30);

        FONT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login2.jpg"))); // NOI18N
        getContentPane().add(FONT);
        FONT.setBounds(0, -40, 690, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        SeConnecter acceuille = new SeConnecter();
        acceuille.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_RetourActionPerformed

    private void SEConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEConnecterActionPerformed
                
        String login = textLogin.getText();
        String INE = textINE.getText();
                try{
                     if(login.isEmpty() || INE.isEmpty()){
                         errorLogin.setText("Champ vide !");
                         errorINE.setText("Champ vide !");  
                         messageEror.setText("veuillez remplir les champs");
                          JOptionPane.showMessageDialog(null,"ECHEC! connexion",null,JOptionPane.ERROR_MESSAGE);
                    }
                     else{
                         connexion conect = new connexion();//  connection a la base de donnee
                         pst = conect.con.prepareStatement("select * from Etudiant where INE =? and login=?");
                         pst.setString(1, INE);
                         pst.setString(2, login);
                         rs=pst.executeQuery();
                         if(!rs.isBeforeFirst()){//donnees existe pas
                             messageEror.setText("ce compte n'existe pas");
                             errorLogin.setText("");
                             errorINE.setText("");
                         }
                         else{// si les donnees sont dans la bases de donnes 
                             while(rs.next()){
                               // login.super.dispose();
                               AcceuilEtudiant pageAcceuil = new AcceuilEtudiant();
                               pageAcceuil.setVisible(true);
                               setVisible(false);
                             }
                         }
                     }
                 }
                 catch(Exception e){
                     e.printStackTrace();
                             }
    }//GEN-LAST:event_SEConnecterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageDeconnexion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageDeconnexion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageDeconnexion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageDeconnexion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageDeconnexion1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONT;
    private javax.swing.JLabel INE;
    private javax.swing.JLabel MOTDEPASSE;
    private javax.swing.JButton Retour;
    private javax.swing.JButton SEConnecter;
    private javax.swing.JLabel errorINE;
    private javax.swing.JLabel errorLogin;
    private javax.swing.JLabel messageEror;
    private javax.swing.JTextField textINE;
    private javax.swing.JTextField textLogin;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
