/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;

/**
 *
 * @author LATYR
 */
public class SeConnecter extends javax.swing.JFrame {

    /**
     * Creates new form SeConnecter
     */
    public SeConnecter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bouttonEtudiant = new javax.swing.JButton();
        retour1 = new javax.swing.JButton();
        titre = new javax.swing.JLabel();
        Admin = new javax.swing.JButton();
        enseignant = new javax.swing.JButton();
        font = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 90));
        setMinimumSize(new java.awt.Dimension(623, 590));
        getContentPane().setLayout(null);

        bouttonEtudiant.setBackground(new java.awt.Color(0, 153, 153));
        bouttonEtudiant.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bouttonEtudiant.setForeground(new java.awt.Color(255, 255, 255));
        bouttonEtudiant.setText("ETUDIANT");
        bouttonEtudiant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        bouttonEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonEtudiantActionPerformed(evt);
            }
        });
        getContentPane().add(bouttonEtudiant);
        bouttonEtudiant.setBounds(420, 340, 150, 40);

        retour1.setBackground(new java.awt.Color(0, 153, 153));
        retour1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        retour1.setForeground(new java.awt.Color(255, 255, 255));
        retour1.setText("RETOUR");
        retour1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        retour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour1ActionPerformed(evt);
            }
        });
        getContentPane().add(retour1);
        retour1.setBounds(180, 430, 210, 40);

        titre.setBackground(new java.awt.Color(204, 204, 204));
        titre.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(102, 102, 102));
        titre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titre.setText("CONNEXION...");
        getContentPane().add(titre);
        titre.setBounds(260, 30, 200, 70);

        Admin.setBackground(new java.awt.Color(0, 153, 153));
        Admin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 255, 255));
        Admin.setText("ADMIN");
        Admin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        Admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminActionPerformed(evt);
            }
        });
        getContentPane().add(Admin);
        Admin.setBounds(10, 340, 160, 40);

        enseignant.setBackground(new java.awt.Color(0, 153, 153));
        enseignant.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enseignant.setForeground(new java.awt.Color(255, 255, 255));
        enseignant.setText("ENSEIGNANT");
        enseignant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        enseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enseignantActionPerformed(evt);
            }
        });
        getContentPane().add(enseignant);
        enseignant.setBounds(220, 340, 150, 40);

        font.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login2.jpg"))); // NOI18N
        getContentPane().add(font);
        font.setBounds(0, -40, 670, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bouttonEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonEtudiantActionPerformed
      PageDeconnexion1 SeConnecter= new PageDeconnexion1();
      SeConnecter.setVisible(true);
      setVisible(false);
    }//GEN-LAST:event_bouttonEtudiantActionPerformed

    private void retour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour1ActionPerformed
       
        welcomePage acceuille = new welcomePage();
        acceuille.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_retour1ActionPerformed

    private void AdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminActionPerformed
       // affiche du formulaire de connection pour les admins
       connectionAdmin adminconect = new connectionAdmin();
       adminconect.setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_AdminActionPerformed

    private void enseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enseignantActionPerformed
     
         // affiche du formulaire de connection pour les enseignants
        connectionProffesseur conectProf = new connectionProffesseur();
        conectProf.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_enseignantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeConnecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeConnecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeConnecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeConnecter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeConnecter().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin;
    private javax.swing.JButton bouttonEtudiant;
    private javax.swing.JButton enseignant;
    private javax.swing.JLabel font;
    private javax.swing.JButton retour1;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
