/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion.des.délibérations;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LATYR
 */
public class welcomePage extends javax.swing.JFrame {

    /**
     * Creates new form welcomePage
     */
    public welcomePage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitreGestionDeliberation = new javax.swing.JLabel();
        BoutonSeConnecter = new javax.swing.JButton();
        Quitter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 90));
        setMinimumSize(new java.awt.Dimension(623, 590));
        getContentPane().setLayout(null);

        TitreGestionDeliberation.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        TitreGestionDeliberation.setForeground(new java.awt.Color(102, 102, 102));
        TitreGestionDeliberation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitreGestionDeliberation.setText("GESTION DES DELIBERATIONS");
        getContentPane().add(TitreGestionDeliberation);
        TitreGestionDeliberation.setBounds(180, 40, 380, 80);

        BoutonSeConnecter.setBackground(new java.awt.Color(0, 153, 204));
        BoutonSeConnecter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BoutonSeConnecter.setForeground(new java.awt.Color(255, 255, 255));
        BoutonSeConnecter.setText("SE CONNECTER");
        BoutonSeConnecter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        BoutonSeConnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonSeConnecterActionPerformed(evt);
            }
        });
        getContentPane().add(BoutonSeConnecter);
        BoutonSeConnecter.setBounds(330, 330, 210, 40);

        Quitter.setBackground(new java.awt.Color(0, 153, 204));
        Quitter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Quitter.setForeground(new java.awt.Color(255, 255, 255));
        Quitter.setText("QUITTER");
        Quitter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        Quitter.setDoubleBuffered(true);
        Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitterActionPerformed(evt);
            }
        });
        getContentPane().add(Quitter);
        Quitter.setBounds(50, 330, 210, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 720, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonSeConnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonSeConnecterActionPerformed
               
        SeConnecter frame1= new SeConnecter();
        frame1.setVisible(true);
       setVisible(false);
                
                 
                 
    }//GEN-LAST:event_BoutonSeConnecterActionPerformed

    private void QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitterActionPerformed
       
        int rep;
        rep = JOptionPane.showConfirmDialog(null,"ête-vous sûre de vouloir quitter! ");
        do{    
        
        System.exit(0);
        
        }while(rep == JOptionPane.YES_NO_OPTION);
        
    }//GEN-LAST:event_QuitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonSeConnecter;
    private javax.swing.JButton Quitter;
    private javax.swing.JLabel TitreGestionDeliberation;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
